### ISSUE TITLE
项目启动时初始化功能权限时间太长;

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/osharp#100]
**描述一下BUG**
项目启动时初始化功能权限时间太长;

**期望行为**
能否提供禁用相关功能开关或优化相关初始化策略

**截图**
![image](https://user-images.githubusercontent.com/9816794/59149916-56cf0200-8a4e-11e9-8585-f8d6b80d4537.png)

**附加上下文，如截图**

**运行环境**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by gmf520** [comment]
第一次运行不要以调试的方式来运行，不会慢的
