### ISSUE TITLE
默认配置 的 Hangfire 明明是关着的为什么还要去连Hangfire 的数据库呢？

### ISSUE THREAD

**Issue by hyzx86** [dotnetcore/osharp#104]
请问这个要怎么关呢？
![image](https://user-images.githubusercontent.com/15613121/62644873-ba59ab00-b97d-11e9-9646-5735ff59098f.png)
![image](https://user-images.githubusercontent.com/15613121/62644901-ca718a80-b97d-11e9-953b-84e556a5a2ee.png)

**Comment by gmf520** [comment]
根据你的图，显然不对，连接串的用户是test，上面报的是sa

**Comment by hyzx86** [comment]
呃。可能是还有其他位置的配置字符串没改

**Comment by hyzx86** [comment]
默认用的是里面这个配置~~

![image](https://user-images.githubusercontent.com/15613121/62673752-3382ed80-b9d2-11e9-84d6-5f3653d70b70.png)

**Comment by gmf520** [comment]
@hyzx86 开发版当然优先用这个配置的东西

**Comment by hyzx86** [comment]
习惯了ABP。。默认吧这个当成生产配置了~
