### ISSUE TITLE
增加Redis对分布式锁的支持

### ISSUE THREAD

**Issue by willtoto** [dotnetcore/osharp#116]
项目里面难免会用到锁  项目为了保证可靠性  搞2台机器发布 然后用到锁的地方就悲剧了
希望增加分布式锁的支持

**Comment by willtoto** [comment]
https://www.cnblogs.com/runningsmallguo/p/10322315.html

CSRedisClient.cs有一个分布锁方法：
/// <summary>
/// 开启分布式锁，若超时返回null
/// </summary>
/// <param name="name">锁名称</param>
/// <param name="timeoutSeconds">超时（秒）</param>
/// <returns></returns>
public CSRedisClientLock Lock(string name, int timeoutSeconds) {
	name = $"CSRedisClientLock:{name}";
	var startTime = DateTime.Now;
	while (DateTime.Now.Subtract(startTime).TotalSeconds < timeoutSeconds) {
		if (this.Set(name, 1, timeoutSeconds, RedisExistence.Nx) == true) {
			return new CSRedisClientLock { Name = name, _client = this };
		}
		Thread.CurrentThread.Join(3);
	}
	return null;
}

CSRedisClientLock现实 IDispose 解锁（删除key）

**Comment by gmf520** [comment]
https://github.com/i66soft/osharp/commit/4dc112fce29adbef16fc0b4de6d0d3523305e5ee
