### ISSUE TITLE
基于cookie的登录问题,User.Identity.IsAuthenticated 仍然是false

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/osharp#117]
**描述一下BUG**
当我调用_signInManager.SignInAsync写入登录cookie时，cookie信息是写入成功的，但是请求时Profile中的User.Identity.IsAuthenticated 仍然是false,是我的调用姿势不对吗
**重现步骤**
`[HttpPost]
        [ModuleInfo]
        [Description("用户登录")]
        public async Task<IActionResult> GoLogin(LoginDto dto)
        {
            IRecaptchaService _recaptcha = null;
            Check.NotNull(dto, nameof(dto));
            if (_recaptcha != null)
            {
                dto.IsCaptcha = true;
                var recaptcha = await _recaptcha.Validate(Request);
                if (!recaptcha.success)
                {
                    ModelState.AddModelError("Recaptcha", "验证码错误,请确认重试");
                    return View(dto);
                }
            }
            dto.Ip = HttpContext.GetClientIp();
            dto.UserAgent = Request.Headers["User-Agent"].FirstOrDefault();
            OperationResult<User> result = await _identityContract.Login(dto);
            IUnitOfWork unitOfWork = HttpContext.RequestServices.GetUnitOfWork<User, int>();
            unitOfWork.Commit();
            if (!result.Succeeded)
            {
                ModelState.AddModelError("Account", result.Message);
                //return View(dto);
                return RedirectToAction("Login", dto);
            }
            User user = result.Data;

            await _signInManager.SignInAsync(user, dto.Remember);
            //var temp = Profile();
            return RedirectToAction("Index", "Home");
        }`
`  [HttpGet]
        [ModuleInfo]
        [Description("用户信息")]
        public async Task<OnlineUser> Profile()
        {
            var data = HttpContext.User;
            if (!User.Identity.IsAuthenticated)
            {
                return null;
            }

            IOnlineUserProvider onlineUserProvider = HttpContext.RequestServices.GetService<IOnlineUserProvider>();
            if (onlineUserProvider == null)
            {
                return null;
            }
            OnlineUser onlineUser = await onlineUserProvider.GetOrCreate(User.Identity.Name);
            onlineUser.RefreshTokens.Clear();

            return onlineUser;
        }`
**期望行为**
User.Identity.IsAuthenticated 应该为true

**截图**

**附加上下文，如截图**
![image](https://user-images.githubusercontent.com/9816794/67544373-bf7df900-f727-11e9-8b11-a3125343e3e2.png)

**运行环境**

**Desktop (please complete the following information):**
 - Version 1.0.1

**Comment by 491134648** [comment]
已经处理,与jwt冲突了，在cookie中写入jwttoken，在identitypack中解析cookie或session的指定key的值，赋值给context.token

**Comment by gmf520** [comment]
框架本身只使用了jwt，还没有考虑cookie的方式，待优化

**Comment by gmf520** [comment]
https://github.com/dotnetcore/OSharp/commit/e28cfb726429626d7d254d6666c6581fbfa1c30e
