### ISSUE TITLE
UnitOfWork中Rollback方法改进点

### ISSUE THREAD

**Issue by Champion-Chen** [dotnetcore/osharp#118]
虽然这个方法几乎不被用到，但我无聊还是测试了下，有点问题可以改进下：
```
if (_transaction?.Connection != null)
{
    _transaction.Rollback();
}
foreach (var context in _dbContexts)
{
    if (context.IsRelationalTransaction())
    {
        CleanChanges(context);
        if (context.Database.CurrentTransaction != null)
        {
            context.Database.CurrentTransaction.Rollback();
            context.Database.CurrentTransaction.Dispose();
        }
        continue;
    }
    context.Database.RollbackTransaction();
}
HasCommitted = true;

```
1. transaction rollback后，context.Database.CurrentTransaction再次RollBack会报错，提示已回滚，无需再次Rollback;
2. CurrentTransaction.Rollback()执行后，CurrentTransaction值会变为null，再次执行Dispose会报错。

改进：1 前面的Rollback去掉；2 Dispose去掉；

**Comment by gmf520** [comment]
这个问题在新版本中已经修复了
https://github.com/i66soft/osharp/blob/master/src/OSharp.EntityFrameworkCore/UnitOfWork.cs#L210
主要是去掉了`context.Database.CurrentTransaction.Rollback();`
