### ISSUE TITLE
运行Demo.Web报错

### ISSUE THREAD

**Issue by zhonghy** [dotnetcore/osharp#119]
复制源码下来，运行里面的Demo.Web项目，页面打开报404错误，数据库采用sqlserver2014

**Comment by zhonghy** [comment]
错误：

**Comment by qinqoushui** [comment]
我用的是LOCALDB模式，也是404了，SWAGGER没有问题，也没有其它抛错，不知道如何解决

**Comment by gmf520** [comment]
查看IIS Express启动页是否指向Swagger的默认路径，默认路径是 /swagger/index.html
