### ISSUE TITLE
数据权限实现方式

### ISSUE THREAD

**Issue by TonnyGu** [dotnetcore/osharp#12]
请问下数据权限的实现方式有思路了吗？

**Comment by gmf520** [comment]
已经提交了大部分实现代码了，稍后会专门写篇文档来详述实现方案 
3dafcad8e130f5be274bfeeaba8405198248d863
5416c7f218585b2fc43b9514efcab9521a293e17
94ae7f25e79cacca0631b3b5e328aadf7f91e4d9
148bcd27d33f285b9d78f37098c1fd237c568eae
