### ISSUE TITLE
打开Swagger页面，Debug时报错

### ISSUE THREAD

**Issue by hwubin5** [dotnetcore/osharp#123]
**描述一下BUG**
在windows 10 上，运行正常。在mac上，debug时打开swagger页面会报错；dotnet run 时，似乎服务正常启动了，但是无法打开swagger站点。

**重现步骤**
1.下载最新3.0版代码；
2.在Liuliu.Demo.Web项目中，将配置改为mysql；
3.将部分字段限制最大字符数。用于解决之前提的mysql 8.0.17迁移报错的问题；
4.执行数据迁移操作；
5.dotnet run 项目；
6.执行过程正常，但没有提示站点服务启动成功，也没有显示站点默认地址；
7.停止服务；
8.debug项目，一切正常；
9.在浏览器中输入：http://localhost:5000/swagger/index.html
10.报错停止；如下图示；

**期望行为**
1.无论是debug或者正常的dotnet run，启动服务后应该都提示站点提示；
2.项目似乎对mysql和vscode + mac环境支持不好。同样的操作，在win10+vs2019就没事。

**截图**
![image](https://user-images.githubusercontent.com/32081793/68085350-0b911200-fe7b-11e9-9303-ef322b8f5387.png)

![image](https://user-images.githubusercontent.com/32081793/68085341-fb793280-fe7a-11e9-8e55-422d05b4d76d.png)
如图，debug时会报此错误，跳过后可以正常打开页面；

![image](https://user-images.githubusercontent.com/32081793/68085382-5f036000-fe7b-11e9-9a03-5a623f450a5f.png)
![image](https://user-images.githubusercontent.com/32081793/68085391-704c6c80-fe7b-11e9-8a43-7b6e06aec7a1.png)

如上图，正常的dotnet run，则无法打开页面。

**运行环境**

macos+vscode+mysql 8.0.17

**Comment by warriorsfly** [comment]
我也遇到了类似的情况,
但**我个人觉得这不是osharp的错**,在macos上建立的.net core项目可以跑起来,但是windows上建立的.netcore在Mac上从来没跑起来过(没有做太多尝试,4,5次吧,别人的项目拉下来就是跑不起来).所以,我感觉这个是vs或者.netcore的错~
以下是我的log的一部分
      添加功能“9bc00f4a-db2f-4118-ad77-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“e4cf6c0c-293e-4b10-ae9d-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“e4cf6c0c-293e-4b10-ae9d-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“65731a36-d59a-449e-af44-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“65731a36-d59a-449e-af44-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“e9521ea3-acad-48fb-b245-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“e9521ea3-acad-48fb-b245-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“e5c96cb1-43cd-4078-b2d1-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“e5c96cb1-43cd-4078-b2d1-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“fffa8e2c-3ad1-472f-b340-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“fffa8e2c-3ad1-472f-b340-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“9a43940e-3ca7-43c3-b554-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“9a43940e-3ca7-43c3-b554-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“03c875cb-e3f7-4807-b643-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“03c875cb-e3f7-4807-b643-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“3842b3be-df89-4b56-b756-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“3842b3be-df89-4b56-b756-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“35142faa-2911-4637-ba35-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“35142faa-2911-4637-ba35-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“29b7e268-d02c-4957-ba9d-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“29b7e268-d02c-4957-ba9d-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“8abf8fc8-4d25-4141-baee-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“8abf8fc8-4d25-4141-baee-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“438175d8-b442-4d25-bbc4-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“438175d8-b442-4d25-bbc4-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“bc5f858c-35ca-48ec-bbf0-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“bc5f858c-35ca-48ec-bbf0-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“8032c113-53b6-4a1b-bde0-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“8032c113-53b6-4a1b-bde0-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“6d2afdce-b270-4f1a-bde1-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“6d2afdce-b270-4f1a-bde1-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“81768660-7fe4-4b48-bef7-ab8b00d9be30”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“81768660-7fe4-4b48-bef7-ab8b00d9be30”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“de0f0d28-164a-41e6-812c-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“de0f0d28-164a-41e6-812c-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“386b6789-478e-4ccd-8855-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“386b6789-478e-4ccd-8855-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“7451e955-9626-445f-8922-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“7451e955-9626-445f-8922-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“13b72eed-a959-4801-8d4a-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“13b72eed-a959-4801-8d4a-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“71227837-d451-4d96-8f41-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“71227837-d451-4d96-8f41-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“2ef9c753-cad3-4d46-92dc-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“2ef9c753-cad3-4d46-92dc-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“20cdfd0b-8fd7-4dd5-94cb-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“20cdfd0b-8fd7-4dd5-94cb-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“8ebbfcf8-b774-499d-9587-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“8ebbfcf8-b774-499d-9587-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“8237b9c7-7972-4b0b-9837-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“8237b9c7-7972-4b0b-9837-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“fc82d1ff-cbeb-40fe-a102-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“fc82d1ff-cbeb-40fe-a102-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“bec84eca-27be-4a30-a281-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“bec84eca-27be-4a30-a281-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“6677cef2-4f49-485c-a35b-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“6677cef2-4f49-485c-a35b-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“e4901d2d-32ac-4058-a3c6-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“e4901d2d-32ac-4058-a3c6-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“a62d5f79-f829-4270-ab5c-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“a62d5f79-f829-4270-ab5c-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“08a58aa5-b34b-438a-b2c1-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“08a58aa5-b34b-438a-b2c1-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“74bf1ecd-6f93-4979-b362-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“74bf1ecd-6f93-4979-b362-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“4680a6d5-f032-4d62-b40b-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“4680a6d5-f032-4d62-b40b-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“229573d5-2f5a-4a51-b45f-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“229573d5-2f5a-4a51-b45f-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“77ee107e-a952-4ccc-b563-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“77ee107e-a952-4ccc-b563-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“c6b57f89-8855-41b2-b616-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“c6b57f89-8855-41b2-b616-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“1bf55e84-822c-47f9-baf4-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“1bf55e84-822c-47f9-baf4-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“644a62a4-b3cc-4648-bc5e-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“644a62a4-b3cc-4648-bc5e-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“79d0dc8b-8a32-4249-bd74-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“79d0dc8b-8a32-4249-bd74-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Debug: 添加功能“a2db6ba3-6be4-4d50-be48-ab8b00d9be31”的“Function-Roles[]”缓存
dbug: WX.REMSS.Authorization.FunctionAuthCache[0]
      添加功能“a2db6ba3-6be4-4d50-be48-ab8b00d9be31”的“Function-Roles[]”缓存
WX.REMSS.Authorization.FunctionAuthCache: Information: 功能权限：创建107个功能的“Function-Roles[]”缓存
info: WX.REMSS.Authorization.FunctionAuthCache[0]
      功能权限：创建107个功能的“Function-Roles[]”缓存
WX.REMSS.Authorization.DataAuthCache: Information: 数据权限：创建0个数据权限过滤规则缓存
info: WX.REMSS.Authorization.DataAuthCache[0]
      数据权限：创建0个数据权限过滤规则缓存
WX.REMSS.Authorization.ModuleHandler: Information: 98条基础数据“OSharp.Authorization.Modules.ModuleInfo”的内容签名 bbe110790251dac5e8c947fb9de21d4e 与上次相同，取消数据库同步
info: WX.REMSS.Authorization.ModuleHandler[0]
      98条基础数据“OSharp.Authorization.Modules.ModuleInfo”的内容签名 bbe110790251dac5e8c947fb9de21d4e 与上次相同，取消数据库同步
WX.REMSS.Authorization.ModuleHandler: Information: 同步模块数据时，数据签名与上次相同，取消同步
info: WX.REMSS.Authorization.ModuleHandler[0]
      同步模块数据时，数据签名与上次相同，取消同步
OSharp.AspNetCore.AspOsharpPackManager: Information: Osharp框架初始化完成，耗时：0:00:28.823718
info: OSharp.AspNetCore.AspOsharpPackManager[0]
      Osharp框架初始化完成，耗时：0:00:28.823718
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.2/Microsoft.Extensions.FileProviders.Embedded.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.2/Microsoft.AspNetCore.Diagnostics.Abstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.2/Microsoft.AspNetCore.Http.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/Users/walker/Coding/Work/Wxsoft/remss/src/WX.REMSS.Web/bin/Debug/netcoreapp3.1/Microsoft.IdentityModel.Tokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/Users/walker/Coding/Work/Wxsoft/remss/src/WX.REMSS.Web/bin/Debug/netcoreapp3.1/System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/Users/walker/Coding/Work/Wxsoft/remss/src/WX.REMSS.Web/bin/Debug/netcoreapp3.1/Microsoft.IdentityModel.Logging.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/Users/walker/Coding/Work/Wxsoft/remss/src/WX.REMSS.Web/bin/Debug/netcoreapp3.1/Microsoft.IdentityModel.Protocols.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/Users/walker/Coding/Work/Wxsoft/remss/src/WX.REMSS.Web/bin/Debug/netcoreapp3.1/Microsoft.IdentityModel.Protocols.OpenIdConnect.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/3.1.2/Microsoft.AspNetCore.WebUtilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.2/System.Net.WebSockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 720205 has exited with code 0 (0x0).
The thread 719681 has exited with code 0 (0x0).
The thread 720206 has exited with code 0 (0x0).
The thread 720195 has exited with code 0 (0x0).
The thread 711173 has exited with code 0 (0x0).
The thread 710529 has exited with code 0 (0x0).
The thread 711164 has exited with code 0 (0x0).
The thread 715010 has exited with code 0 (0x0).
The thread 744097 has exited with code 0 (0x0).
The thread 744092 has exited with code 0 (0x0).
The thread 744091 has exited with code 0 (0x0).

**Comment by gmf520** [comment]
我偶尔遇到过，无法重现，看起来是Swagger引入了`MiniProfiler`引起的，可以尝试关闭Swagger的`MiniProfiler`，在appsetting(.development).json中，配置如下：
```
"OSharp": {
...
 Swagger: {
  ...
  "MiniProfiler": false
  ...
}
...
}

```

**Comment by warriorsfly** [comment]
> 我偶尔遇到过，无法重现，看起来是Swagger引入了`MiniProfiler`引起的，可以尝试关闭Swagger的`MiniProfiler`，在appsetting(.development).json中，配置如下：
> 
> ```
> "OSharp": {
> ...
>  Swagger: {
>   ...
>   "MiniProfiler": false
>   ...
> }
> ...
> }
> ```

我借了一台windows,虽然用不惯,也懒得折腾了
