### ISSUE TITLE
项目模版生成后，迁移数据库报错

### ISSUE THREAD

**Issue by 575594155** [dotnetcore/osharp#136]
生成模版，生成解决方案，我就改了数据库连接字符串，执行迁移就报错
![image](https://user-images.githubusercontent.com/39397748/76762340-1619cb80-67cc-11ea-865d-eb71b6258092.png)

**Comment by gmf520** [comment]
![image](https://user-images.githubusercontent.com/3930317/76762902-1ebed180-67cd-11ea-852b-b827f91a6241.png)

请确认你项目中如上图所使用的数据库驱动与要连接的数据库是否匹配

**Comment by 575594155** [comment]
可以了  谢谢     
这边默认是用MySql，生成项目后这两个的命名空间并没有改掉
![image](https://user-images.githubusercontent.com/39397748/76764298-86761c00-67cf-11ea-9fa3-afbdd2e01206.png)

**Comment by gmf520** [comment]
好的，多谢反馈
