### ISSUE TITLE
认证和授权

### ISSUE THREAD

**Issue by jiangyimin** [dotnetcore/osharp#137]
1. 用户登出后，是否应该删除UserToken中所有此用户ID的记录

2. 前端的access-token 无感刷新的处理： 用http的拦截器来实现是否好一些

**Comment by gmf520** [comment]
1. 同一个用户在不同的客户端登录，会生成不同的RefreshToken，各个客户端的刷新时间都各不相同，不应移除所有RefreshToken记录
2. 现在的机制是拦截器被动刷新和心跳主动刷新两个方式相结合的
