### ISSUE TITLE
新用户注册失败

### ISSUE THREAD

**Issue by qmtdlt** [dotnetcore/osharp#138]
**项目已正常运行，swagger显示正常，新用户第一次注册时失败**

错误信息：Mailbox name not allowed. The server response was: authentication is required

**Comment by qmtdlt** [comment]
通过test接口注册用户，已经能够登录

**Comment by gmf520** [comment]
由于阿里云禁用非SSL的方式发送邮件，发邮件功能失效导致的，自行换个SMTP即可，这个问题稍后也会修复
