### ISSUE TITLE
代码生成工具

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#155]
代码生成工具如何使用，能不能写个教程或者文档

**Comment by gmf520** [comment]
代码生成器的下载页面有说明
[https://marketplace.visualstudio.com/items?itemName=LiuliuSoft.osharp](https://marketplace.visualstudio.com/items?itemName=LiuliuSoft.osharp)

**Comment by 240011814** [comment]
上面的介绍还是老版本的
