### ISSUE TITLE
代码生成工具

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#157]
代码生成工具使用的时候，点击勾选项的时候，经常自动排序，勾选很难操作

**Comment by gmf520** [comment]
是有这个BUG，规避的做法就是点其他行的时候确保当前行不在编辑状态，就不会触发排序了

**Comment by qinqoushui** [comment]
具体操作就是：编辑完成后不要点到其它行去，可以点下同行的其它单元格
