### ISSUE TITLE
业务代码疑问

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#160]
使用代码生成器的代码，我的业务层该写在哪里？这个框架设计的是写在baseservice ，还是packservice里面，以及接口该添加在哪里，写在iContract里面，就必须在baseservice里面实现，代码生成就会覆盖掉

**Comment by 240011814** [comment]
还是需要自己写个接口文件，取额外的实现？

**Comment by gmf520** [comment]
1. 生成的文件分 *.generated.cs 和 *.cs 文件
2. generated.cs 文件在下次生成的时候会被覆盖，所以不要改动
3. 可以创建或更改相同类型名的 *.cs 文件，这些文件不会被覆盖

**Comment by gmf520** [comment]
看看每个生成文件顶部的 auto-generated 信息，每个文件都有相应的扩展说明，以Infos为例
1. 需要扩展实体类，给实体添加属性，例如 Message.generated.cs，新建分部类 Message.cs 添加属性
2. 需要添加功能，添加接口 IInfosContract.generated.cs 的分部接口 IInfosContract.cs 添加功能
3. 需要重写业务逻辑的默认实现，在 InfosService 继承重写 InfosServiceBase.generated.cs 中的默认实现，这里的修改再次生成不会被覆盖
4. 有不明白的看看相应文件的顶部说明注释，有详细的操作解释

实体类 Message.generated.cs
```
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类：可遵守如下规则进行扩展：
//      1.横向扩展：如需添加额外的属性，可新建文件“Message.cs”的分部类“public partial class Message”}添加属性
// </auto-generated>
```
业务接口 IInfosContract.generated.cs
```
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1. 横向扩展：如需给当前模块添加方法接口，可新建文件“IInfosContract.cs”的分部接口“public partial interface IInfosContract”添加方法，并添加相应新的分部基类 abstract partial class InfosServiceBase 实现新方法
// </auto-generated>
```
业务逻辑基本实现 InfosServiceBase.generated.cs
```
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，请在继承类型 InfosService 进行继承重写
// </auto-generated>
```
业务层重新实现 InfosService.cs
```
// <once-generated>
//     这个文件只生成一次，再次生成不会被覆盖。
//     可以在此类进行继承重写来扩展基类 InfosServiceBase
// </once-generated>
```

**Comment by 240011814** [comment]
明白了

**Comment by 240011814** [comment]
我在servicebase里面注入了服务，为什么一直是null，在moduleservice里面可以正常注入

**Comment by gmf520** [comment]
在上层注入，传参到基类

**Comment by 240011814** [comment]
不是很明白，能给个示例不
