### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#162]
这个怎样实现不查询，直接更新，我记得ef core是有个attch方法，现在找不到了，还有就是如果要调用sql语句，这个用哪个方法

**Comment by gmf520** [comment]
Repository 中有 UpdateBetch方法，是通过EF.Plus实现的，可以用于不查询直接更新的批量更新
```
/// <summary>
/// 批量更新所有符合特定条件的实体
/// </summary>
/// <param name="predicate">查询条件的谓语表达式</param>
/// <param name="updateExpression">属性更新表达式</param>
/// <returns>操作影响的行数</returns>
int UpdateBatch(Expression<Func<TEntity, bool>> predicate, Expression<Func<TEntity, TEntity>> updateExpression);
```

**Comment by 240011814** [comment]
我怎样才能取到ef core的那个dbcontext？

**Comment by gmf520** [comment]
> 我怎样才能取到ef core的那个dbcontext？

`DbContext` 在O#中的默认实现是`DefaultDbContext`，你可以有几种方式获取到这个对象
1. 如果你的项目只使用O#默认的`DefaultDbContext`，可以直接在构造函数注入 `DefaultDbContext`，在一个Scoped范围内获取的都是同一个对象
2. 如果存在自定义上下文，需要区分实体类属于哪个上下文，注入`IUnitOfWorkManager`，通过`manager.GetDbContext<TEntity, TKey>()` 传入指定实体类获取所属上下文
