### ISSUE TITLE
DependOnFunction 疑惑

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#172]
DependOnFunction  加上了这个是方法会先执行这个里面的方法吗？如果是，这个参数又是如何传递的？

**Comment by gmf520** [comment]
@240011814 不会执行，DependOnFunction的意思是，要实现当前功能，需要信赖于其他前置功能，才能完成当前功能的业务，比如：
1. 用户注册，需要信赖于用户名验证的功能，于是Register信赖于CheckUserNameExists
2. 管理页修改用户，需要先能读取用户列表，于是Update信赖于Read
等等，只是业务逻辑上的信赖
这个信赖在授权的时候会使用到，减少授权操作的工作量，比如对管理员授权修改功能，会根据信赖自动授权读取列表功能，以使整个授权操作是完整的

**Comment by 240011814** [comment]
哦，明白了
