### ISSUE TITLE
未发现任何数据上下文实体映射配置

### ISSUE THREAD

**Issue by 527fanqie** [dotnetcore/osharp#188]
未发现任何数据上下文实体映射配置，请通过对各个实体继承基类“EntityTypeConfigurationBase<TEntity, TKey>”以使实体加载到上下文中

你好，跟随文档进行配置后，启动 7001 项目报错，请问我这里遗漏了什么配置吗？

**Comment by gmf520** [comment]
请确保appsetting中的配置，和使用的EFCore驱动Pack（Liuliu.Demo.Web/Startups/）是一致的
#136
