### ISSUE TITLE
3.1.7版的登录接口存在缺陷

### ISSUE THREAD

**Issue by allentan3** [dotnetcore/osharp#194]
### 描述一下BUG
3.1.7版的登录接口存在缺陷.

### 重现步骤
重现步骤如下:
1. 设置Liuliu.Demo.Web为启动项目，然后运行该项目进行调试
2. 在swagger页面中调用/api/Identity/Token接口进行登录，得到返回的AccessToken
3. 然后在这个接口/api/Identity/Profile中填入获取到的AccessToken值并调用该接口，以获取用户信息，结果返回204错误，发现后台的User.Identity.IsAuthenticated显示为false,未正确获取到用户信息。
4. 该问题仅存在于3.1.7版中，在3.1.3和3.1.2版中能正确获取到用户信息。

### 期望行为
能修复3.1.7版中的登录问题，实现正常的登录操作.

**Comment by gmf520** [comment]
原因是需要同时支持Jwt和Cookie，需要指定Schema
暂时可以通过在Controller或其基类上添加如下Attribute解决，这个在后续更新中将会改善
```
[Authorize(Policy = FunctionRequirement.OsharpPolicy, AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
```

**Comment by gmf520** [comment]
已修复
