### ISSUE TITLE
ArgumentException: The 'ClientId' option must be provided

### ISSUE THREAD

**Issue by ArcherTrister** [dotnetcore/osharp#21]
运行demo报错
An unhandled exception occurred while processing the request.
ArgumentException: The 'ClientId' option must be provided.
Parameter name: ClientId
Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()

这是用了单点登录吗

**Comment by gmf520** [comment]
原因是在`IdentityPack`类中启用了QQ的OAuth2登录配置，而在`appsettings.json`中没有提供相应的Key信息而造成的报错，将`IdentityPack`类中的`AddQQ`相关代码注释掉即可

**Comment by ArcherTrister** [comment]
这个问题已解决，非常感谢，后期是否考虑增加把core层，也就是业务层转为动态webapi呢。
