### ISSUE TITLE
登录成功后事件发布报错

### ISSUE THREAD

**Issue by seamusic** [dotnetcore/osharp#236]
已添加了实体，但还没执行迁移，这个时候登录时是成功的。后续到事件发布里出错。
`
            //触发登录成功事件
            LoginEventData loginEventData = new LoginEventData() { LoginDto = dto, User = user };
            await _eventBus.PublishAsync(loginEventData);
            FunctionAuthCacheRefreshEventData functionAuthCacheRefreshEventData =
                new FunctionAuthCacheRefreshEventData() { UserNames = new[] { user.UserName } };
            await _eventBus.PublishAsync(functionAuthCacheRefreshEventData);    //报错
`

![image](https://user-images.githubusercontent.com/172009/123520540-d1295800-d6e3-11eb-841b-a216c2e94cfe.png)

**Comment by seamusic** [comment]
后续没有再发生了。原因不明。

**Comment by seamusic** [comment]
![image](https://user-images.githubusercontent.com/172009/125183415-1a7fb880-e249-11eb-80aa-1186bf00417a.png)
跟踪代码，发现到最后是无法访问数据库？

**Comment by seamusic** [comment]
在编辑功能时，同样也是有一个eventbus publish报错，如下：
![image](https://user-images.githubusercontent.com/172009/125186307-33de3000-e25c-11eb-86df-1b7dda3e78c8.png)

代码位置：
![image](https://user-images.githubusercontent.com/172009/125186337-7b64bc00-e25c-11eb-90db-71b9baf221b9.png)

**Comment by seamusic** [comment]
大概的原因是，使用了事务，数据库更新后，但未提交。这个时候又发起异步事件，导致事件同时查询的是相同的库，导致等待超期报错。

**Comment by gmf520** [comment]
不知你用的哪个版本，在新版本中已修复
