### ISSUE TITLE
MySql调通的几个步骤，记下若有人看到可以帮忙

### ISSUE THREAD

**Issue by Champion-Chen** [dotnetcore/osharp#29]
1 修改配置文件中的连接字符串

2 修改startups中的两个context类：
`public class MySqlDefaultDbContextMigrationPack : MySqlMigrationModuleBase<DefaultDbContext>`
（昨天晚上似乎发布了新版本，sql版本的基类加上了Pack后缀，Mysql似乎也要加）

`    -- MySqlDesignTimeDefaultDbContextFactory中
    return builder.【UseMySql】(connString, b => b.MigrationsAssembly(entryAssemblyName));`

3 修改Migrations中的ID自增配置，这一步网上的资料相当少，在下面地址找到了（https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/223）：
` Id = table.Column<int>(nullable: false).Annotation("MySql:ValueGeneratedOnAdd", true)`

4 初次插入数据库，可能会因为有中文插入不了：
`ALTER DATABASE database_name CHARACTER SET GBK;`

总算通关了，看到swagger文档了，可以开始研究框架了。

--------------------
现在卡在了前端框架新用户注册这里，使用qq邮箱配置总没有成功，总会报一个错：mail from address must be same as authorization user。
用户名和密码都是对的，smpt服务也开启了，只是qq的端口好像从495改变到过25，但好像mailSender类中，没有设置smtp端口的地方。请问你有用qq邮箱实现过的例子么？

**Comment by gmf520** [comment]
我一直没用过mysql，一会也来试试看

**Comment by gmf520** [comment]
我使用MySql5.7试了一下，框架现在的代码完全可以跑起来的，没有问题。步骤如下：
1. 安装MySql5.7，要启用MySql的utf8编码，即my.ini文件中启用`character-set-server=utf8`配置，重启MySql服务。
2. 将现有的`SqlServerDefaultDbContextMigrationPack`和`SqlServerDesignTimeDefaultDbContextFactory`两个类文件复制一份，更名为`MySqlDefaultDbContextMigrationPack`和`MysqlDesignTimeDefaultDbContextFactory`，将文件内容中的`SqlServer`都替换成`MySql`，因为这两套代码都是服务于同一个上下文类型`DefaultDbContext`的，迁移的时候会重复，所以要将`SqlServerDefaultDbContextMigrationPack`和`SqlServerDesignTimeDefaultDbContextFactory`两个SqlServer的文件从项目中排除掉。
3. 更改配置类`appsettings.json`和`appsettings.Development.json`，确保没有指向上下文`DefaultDbContext`的SqlServer配置节点，注意是两个文件的SqlServer配置节点都要删掉，否则会报“数据上下文配置中存在多个配置节点指向同一个上下文类型”的错误，因为系统初始化时两个文件都会读取的。然后创建MySql的配置节点，示例如下：
```
      "MySql": {
        "DbContextTypeName": "OSharp.Entity.DefaultDbContext,OSharp.EntityFrameworkCore",
        "ConnectionString": "Server=127.0.0.1;UserId=root;Password=abcd123456;Database=osharpns.demo-dev;charset='utf8';Allow User Variables=True",
        "DatabaseType": "MySql",
        "LazyLoadingProxiesEnabled": true,
        "AuditEntityEnabled": true,
        "AutoMigrationEnabled": true
      }
```
4. 然后，当然是通过`Add-Migration XXXX` 命令创建迁移记录了，然后应该就能跑起来。
