### ISSUE TITLE
关于发布订阅模式的疑问

### ISSUE THREAD

**Issue by kinshines** [dotnetcore/osharp#34]
您好，
看了您这套开发框架，受益匪浅，顶礼膜拜，其中关于发布和订阅模式有一点疑问，希望您能解答一下：
若是在一次Web请求中，发布了一个消息，订阅者在处理这条消息时，Web请求已经返回，申请的DBContext资源也已经释放，那么此时订阅者如何再对DBContext执行操作？

**Comment by gmf520** [comment]
访问者的执行，可以根据wait参数，决定是否立即返回，以应对不同的使用场景
同步方法
```
/// <summary>
/// 同步发布指定事件
/// </summary>
/// <typeparam name="TEventData">事件数据类型</typeparam>
/// <param name="eventData">事件数据</param>
/// <param name="wait">是否等待结果返回</param>
void Publish<TEventData>(TEventData eventData, bool wait = true) where TEventData : IEventData;
```
异步方法
```
/// <summary>
/// 异步发布指定事件
/// </summary>
/// <typeparam name="TEventData">事件数据类型</typeparam>
/// <param name="eventData">事件数据</param>
/// <param name="wait">是否等待结果返回</param>
Task PublishAsync<TEventData>(TEventData eventData, bool wait = true) where TEventData : IEventData;
```
建议使用方式如下：
1. 对于数据存储的操作，比如订阅登录成功事件写登录日志，属于整个业务体系的一部分，只是使用EventBus来进行业务解耦，应该使用wait=true
2. 对于非数据库的短时操作，比如订阅登录成功事件发邮件，wait可true可false
3. 对于长时操作，比如订阅登录成功事件给所有好友发通知，可以设置wait=false，然后在订阅端进行Scoped生命周期管理，比如CreateScope创建一个新的Scoped来处理长时操作的数据存储操作，操作执行完之后自行释放Scope

**Comment by gmf520** [comment]
订阅端怎么处理业务，是灵活的，并不一定要依赖于发布端

**Comment by kinshines** [comment]
非常感谢您的回复！
