### ISSUE TITLE
感谢郭老板的分享

### ISSUE THREAD

**Issue by osharpfans** [dotnetcore/osharp#49]
不仅仅是os的开源，最重要的是wx刷量思路的分享让小弟们接触到了灰产行业且在18年实现了小小的财务自由，真心和做梦一样。
感激的话不多说了，受郭老板恩泽的小小工作室的三人组在此祝郭老板新的一年发大财，收入一年更比一年高。

**Comment by gmf520** [comment]
你真厉害，成功属于行动力者

**Comment by novelXX** [comment]
> 不仅仅是os的开源，最重要的是wx刷量思路的分享让小弟们接触到了灰产行业且在18年实现了小小的财务自由，真心和做梦一样。
> 感激的话不多说了，受郭老板恩泽的小小工作室的三人组在此祝郭老板新的一年发大财，收入一年更比一年高。

装X犯，有种你也来分享分享，别光整些没用的，小心哪天进去了有得赚没的花
