### ISSUE TITLE
关于osharp.efcore模块，请问有更多的示例么

### ISSUE THREAD

**Issue by RyanOvO** [dotnetcore/osharp#51]
很想研究下博主的repository-unit of work构成数据访问层的代码，并在项目中使用，想要先从示例程序入手，但是好像只有很少的示例，所以想问下博主有没有osharp.EntityFrameworkCore层的示例。感谢博主的开源

**Comment by gmf520** [comment]
[https://github.com/i66soft/osharp-ns20-samples/tree/master/src/OSharp.Samples.MultipleDbContexts](https://github.com/i66soft/osharp-ns20-samples/tree/master/src/OSharp.Samples.MultipleDbContexts)
这里有一些示例你可以看看，不同数据库多上下文的，基本osharp.efcore的所有知识点都有涉及了

**Comment by RyanOvO** [comment]
好的，感谢楼主
