### ISSUE TITLE
工作单元报错

### ISSUE THREAD

**Issue by RyanOvO** [dotnetcore/osharp#54]
![image](https://user-images.githubusercontent.com/31231960/54510098-02544300-4987-11e9-9942-7d8f2de2af7b.png)
在controller里面应用已注入的IXXXService的时候，直接报错。请问是什么原因？

**Comment by gmf520** [comment]
对于自定义上下文类型，你需要提供相应的上下文配置信息，例如 https://github.com/i66soft/osharp-ns20/blob/eeb9a34d7d1aebfbbcb5f161860e3c92eca02bea/tests/web/Liuliu.Demo.Web/appsettings.Development.json#L17

**Comment by RyanOvO** [comment]
已解决，请问有更详细的框架解说文档么？在博客园上把博主的博客看了好几遍了，还是不能将osharpns理解并使用上.....如果有文档解说各个模块，尤其是工作单元的使用的话，麻烦楼主分享下，谢谢。

**Comment by RyanOvO** [comment]
> 对于自定义上下文类型，你需要提供相应的上下文配置信息，例如
> 
> [osharp-ns20/tests/web/Liuliu.Demo.Web/appsettings.Development.json](https://github.com/i66soft/osharp-ns20/blob/eeb9a34d7d1aebfbbcb5f161860e3c92eca02bea/tests/web/Liuliu.Demo.Web/appsettings.Development.json#L17)
> 
> Line 17 in [eeb9a34](/i66soft/osharp-ns20/commit/eeb9a34d7d1aebfbbcb5f161860e3c92eca02bea)
> 
>  "SqlServer": {


已解决，请问有更详细的框架解说文档么？在博客园上把博主的博客看了好几遍了，还是不能将osharpns理解并使用上.....如果有文档解说各个模块，尤其是工作单元的使用的话，麻烦楼主分享下，谢谢。

**Comment by gmf520** [comment]
@RyanOvO 
这里有一些文档，最近在使用ng-alain做前端UI，搞好之后会推一个框架设计解说系列博客
http://docs.osharp.org/articles/packs/index.html

**Comment by RyanOvO** [comment]
感谢感谢，已收藏。持续关注大神的杰作。

**Comment by RyanOvO** [comment]
@gmf520 感谢感谢，已收藏。持续关注、研究 大神的杰作。
