### ISSUE TITLE
文档优化

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#60]
现阶段文档只能看到个大概，具体里面的各模块关联对新手很不友好，
建议写个文档，从一个功能模块刚起，一步一步的前后端添加流程及权限
还有就是代码生成，看到文档有但不知道如何使用
前段这块我看到数据访问都是写在组件里，建议数据访问写在service里面，用泛型实现一个基本的增删改查和分页的baseservice，后台也实现一个同样的basecontroller，这样基本的增删改查页面定一个实体类，继承下就完事了

**Comment by gmf520** [comment]
1. 有计划在前端搞好之后写个《框架设计详解》和《实战演练》的系列文章
2. 代码有代码生成器的VS插件，现在还不是很完善，https://marketplace.visualstudio.com/items?itemName=LiuliuSoft.osharp
3. 数据查询还是不太建议写在Service层中，数据查询是跟UI层密切相关的，应该是要什么查什么，并且很多关联数据的查询都需要使用Select来进行投影查询，做不到通用。
4. Service层不是控制器与数据层的传声筒，而是系统的真正业务处理的核心层，数据校验，业务处理逻辑都需要在这一层做，CUD也并不能做到泛型通用。另外Service是服务于一个模块的，而不是服务于单个实体，每个模块都有很多实体，每个实体的泛型，都涉及TEntity，TEntityInputDto，TEntityOutputDto，如果做成泛型支持，恐怕会大大增加Service层的复杂度，带来很多的不灵便。一个生动的例子就是 权限组件的 SecurityManagerBase，就搞得挺复杂的。https://github.com/i66soft/osharp/blob/master/src/OSharp.Permissions/Security/SecurityManagerBase.cs

**Comment by 240011814** [comment]
我说的这个只是给单表场景适应的，一般复杂的都是要自己重写的，我看很多java框架的代码生成都是这样整的，推荐你去看下jeesite4，这也是个开源项目，可以互相借鉴下
