### ISSUE TITLE
逻辑删除接口支持

### ISSUE THREAD

**Issue by willtoto** [dotnetcore/osharp#63]
逻辑删除接口支持，最好么再增加审核接口的支持

**Comment by gmf520** [comment]
有逻辑删除的计划，但尚未考虑好实现方案

**Comment by gmf520** [comment]
(efcore)：添加逻辑删除实现：
1. 通过给实体实现 `ISoftDeletable` 接口进行实现，给实体类添加一个 `DeletedTime`属性
2. 当数据进行逻辑删除时，给此属性赋予当前时间
3. 给实现了`ISoftDeletable`接口的实现自动添加一个`DatetedTime == null`的全局查询过滤，数据查询时将自动应用此过滤条件进行查询，保证查询出来的数据都是未逻辑删除的数据
4. 如果有唯一索引需求，则需要在索引属性中加入`DeletedTime`属性作为约束条件，否则无法复用已删除数据，例如用户实体中，要求用户名唯一，则需要添加 `{UserName, DeletedTime}` 的索引约束
