### ISSUE TITLE
建议写个demo示例，简单的做一个功能

### ISSUE THREAD

**Issue by gnsilence** [dotnetcore/osharp#66]
框架需要的知识有点多，希望能写个教程从后台api到前台的实现，尤其是前台的功能添加，可以是一个简单的例子

**Comment by gmf520** [comment]
有计划准备出《框架设计详解》和《框架实战教程》两个系列文章，正在策划，敬请期待

**Comment by gnsilence** [comment]
> 有计划准备出《框架设计详解》和《框架实战教程》两个系列文章，正在策划，敬请期待

好的，期待中

**Comment by gmf520** [comment]
《[OSharp文档中心](https://docs.osharp.org)》已提上日程，欢迎持续关注，也欢迎提PR更新文档
