### ISSUE TITLE
给实体添加创建者和更新者的快速审计信息接口

### ISSUE THREAD

**Issue by s641135196** [dotnetcore/osharp#67]
-在CRUD中常用到下面4个字段，希望能够集成。

- **增加人id**

      增加时自动加上， 可方便筛选出自己增加的数据，也好知道是谁增加的

 **增加时间**:（框架已有）

- **更新人id**

      更新时自动修改为更新人 ，可看更新人是自己的，好筛选数据，也好看是谁改了数据

- **更新时间** 

     更新时自动修改更时间，  可用这字段排序，可看最新更新数据（比较有用）

 如果全用审计的话，感谢有点浪费数据库资源了。有时候也不太方便筛选数据的。
 不知道在框架中好不好搞。 平时都是自己在增加中自动加下增加人， 修改时自动修改为更新人，更新时间。 如果在后台集成。这样又可以少写些代码了。

**Comment by gmf520** [comment]
这些信息本来就是审计类的信息，用审计没啥不好的，如果不关心数据变化，只开操作审计就行了，在相应的功能点`Function`中进行配置。将记录关联到审计信息即可。
光记录一个操作人和操作时间，其实没多大意义，特别是更新人，只能记录最后一个更新者的信息，前面的会被后面的覆盖掉，也不能确实哪些信息是谁改的，意义不大吧。如果用审计，就能看得出数据变更历史了，如果关心变更历史，不存在浪费数据库资源的问题

**Comment by s641135196** [comment]
恩呀，审计的确记录的更全面。 其实这几个字段也不失为另一种选择。
     例如： 在界面显示上一次修改人，增加人啥的也方便。或根据修改人，增加人进行过滤表中的数据。

![image](https://user-images.githubusercontent.com/8079013/56004260-ebdaa680-5cfc-11e9-84e4-81f3e6cf148d.png)

**Comment by gmf520** [comment]
已添加实现：
1. 新增 创建者和创建时间的`ICreationAudited`接口
2. 新增 最后修改者和修改时间的 `IUpdateAudited`
3. 自动确定UserId的类型，目前支持 `int, Guid, long` 数据类型
4. 在`Repository`中检测实体是否实现了相应的接口，如果实现，则自动执行接口的相关逻辑，给相应属性赋值
