### ISSUE TITLE
目前的UI部分vue版本只有基础框架, 十分期待所有功能集成完毕!

### ISSUE THREAD

**Issue by zhi-jun** [dotnetcore/osharp#71]
**您的功能请求与现有问题有关吗？请描述**

**描述您想要的解决方案**

**描述你考虑过的替代方案**

**附加上下文，比如截图**

**Comment by gmf520** [comment]
Vue 版本现在属于挂起状态，还没有时间去做，最近主要搞《[OSharp文档中心](https://docs.osharp.org)》这个站，先完善下文档。
Vue版本社区已经有人做了，[https://github.com/zionLZH/osharpVue3](https://github.com/zionLZH/osharpVue3)，你可以看看

**Comment by zhi-jun** [comment]
社区的这个vue版本,还是有点粗糙
