### ISSUE TITLE
qq登录问题

### ISSUE THREAD

**Issue by ohngahng** [dotnetcore/osharp#74]
**描述一下BUG**
![image](https://user-images.githubusercontent.com/3369417/56863699-4ad23800-69ec-11e9-9897-83e7d79dee5a.png)

**重现步骤**
1. QQ登录 创建账户并绑定
2. 解除绑定QQ
3. 再次登录，就提示这个

**Comment by gmf520** [comment]
已修复，在未设置登录密码时禁止解除唯一的第三方登录方式，用户系统会慢慢完善，现在的流程还有很多小问题
