### ISSUE TITLE
使用OsharpNS项目模板创建项目，源地址检索不到信息

### ISSUE THREAD

**Issue by keepRunM** [dotnetcore/osharp#78]
![image](https://user-images.githubusercontent.com/29815398/57348454-afc62480-7188-11e9-91ca-135f31544e50.png)

**Comment by gmf520** [comment]
@keepRunM 在VS中把没用的nuget源去掉，有用的nuget源是 https://api.nuget.org/v3/index.json

**Comment by keepRunM** [comment]
完美解决，谢谢
