### ISSUE TITLE
当实体主键为非自增字段时，InputDto向实体映射得时候会覆盖实体的Id

### ISSUE THREAD

**Issue by willtoto** [dotnetcore/osharp#81]
var school = new School(); //new的时候 已经对Id进行赋值 9999

        /// <summary>
        /// 初始化Id   在实体初始化的时候初始化Id
        /// </summary>
        public School()
        {
            Id = 9999;
        }

school = dto.MapTo(school);//新建的时候，传过来的Id为0或null，通过此命令 完成映射，此时实体的Id被覆盖，导致存入数据库的数据不符合预期

尝试建立AutoMapperConfiguration 也无效
        /// <summary>
        /// 创建对象映射
        /// </summary>
        /// <param name="mapper">映射配置表达</param>
        public void CreateMaps(MapperConfigurationExpression mapper)
        {
            mapper.CreateMap<SchoolInputDto, School>().ForMember(dest => dest.Id, opt => opt.Condition(src => src.Id.ToLong() > 0));
        }

按照文章https://www.bbsmax.com/A/mo5kbNMJwR/ 配置之后还是无效

**Comment by gmf520** [comment]
调整AutoMapper的映射注册顺序，使通过 IAutoMapperConfiguration 接口自定义配置的优先级大于[MapFrom]，[MapTo] 的Attribute注册
https://github.com/i66soft/osharp/commit/b450747c1051338297ce7b45f7ac739e34b49337
