### ISSUE TITLE
新增Controller后swager报错

### ISSUE THREAD

**Issue by 491134648** [dotnetcore/osharp#84]
**描述一下BUG**
新增Controller后swager报错
**重现步骤**
1. 新增Controller后启动报错
`namespace UnionDeivice.WebApp.Controllers
{
    public class AccountControllerr : ApiController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}`

**期望行为**

**截图**
![image](https://user-images.githubusercontent.com/9816794/57871623-4c995980-783c-11e9-81b1-5054db1dc1b7.png)

**附加上下文，如截图**

**运行环境**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by gmf520** [comment]
请仔细阅读文档 https://docs.osharp.org/quick/steps/controller/

对于Swagger，少了HttpGet或HttpPost

对于Osharp的模块信息构建，少了[ModuleInfo]
