### ISSUE TITLE
OperationResult转AjaxResult丢失Data

### ISSUE THREAD

**Issue by jifeilong9** [dotnetcore/osharp#85]
**描述一下BUG**
OperationResult使用扩展方法ToAjaxResult()转AjaxResult丢失Data
**重现步骤**
OperationResult result =new OperationResult(OperationResultType.Success, "成功", "Data数据");
 result.ToAjaxResult();
//转成AjaxResult()后Data为null
result.Data==null

**期望行为**
群友反应源码中忘加Data的转换

![image](https://user-images.githubusercontent.com/24316291/57899448-b131d400-788f-11e9-973b-bce09db177d9.png)

**Comment by gmf520** [comment]
已修复
https://github.com/i66soft/osharp/commit/14ed0024f41f58469df0e37f5ba47683176f556d
