### ISSUE TITLE
数据保存返回值正常，数据库无变化

### ISSUE THREAD

**Issue by 240011814** [dotnetcore/osharp#88]
调用Repository里面的方法必需加上  [ServiceFilter(typeof(UnitOfWorkAttribute))]  ？
我没加返回值正常，但是数据库无变化

**Comment by gmf520** [comment]
1. 涉及数据库增、删、改操作的业务，都是在事务下进行的，事务在第一次调用增删改的时候自动打开。
2. 有事务，就要提交事务，OSharp设计了一个[UnitOfWork]的Mvc Filter来自动提交事务
3. 如果不用[UnitOfWork]，就需要手动来提交事务了：
```
IUnitOfWork unitOfWork = HttpContext.RequestServices.GetUnitOfWork<TEntity, TKey>();
unitOfWork.Commit();
```
> 1.0版本开始，[ServiceFilter(typeof(UnitOfWorkAttribute))]已经可以简化为[UnitOfWork]了

**Comment by 240011814** [comment]
哦，但是这个返回值没加UnitOfWork 能不能加个异常啥的，不然出错了还是返回正常

**Comment by gmf520** [comment]
这属于对框架了解不足的问题，事务并不是一定要提交，框架不能一刀切的抛异常的
