### ISSUE TITLE
安装中遇到的问题

### ISSUE THREAD

**Issue by Champion-Chen** [dotnetcore/osharp#9]
1 在我的环境中，需要添加version, 否则会报NU1107错误：已安装新的runtime; 
`<PackageReference Include="Microsoft.AspNetCore.App" version="2.1.1"/>`

2 由于我使用的是mysql。修改连接字符串后会报错。原因是sqlserverdesignTimeDefaultDbContext的UseSql方法中已经写死了使用SqlServer。请问该怎么做？

----ps:
很感谢也很高兴国内dotnetcore有这种框架，另外angular6+kendo也很喜欢，祝越来越好。

**Comment by gmf520** [comment]
1. 不懂，通过nuget引用的，应该不会出什么问题
2. MySql的问题，你需要参考SqlServer创建以下两个类，使用相应的MySql基类
```
MySqlDefaultDbContextMigrationModule.cs
MySqlDesignTimeDefaultDbContextFactory
```
很简单，复制SqlServer的版本，SqlServer替换成MySql字符替换就行
另外文件`appsettings.Development.json`中也要启用相应的`OSharp:DbContexts:MySql`的配置

**Comment by Champion-Chen** [comment]
谢谢回复。
1 我将xx.web.csproj文件进行了修改<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.1" />，直接指定了version
2 我按照步骤生成的项目中，依赖项OSharpNS依赖的子依赖中，只看到了OSharpNS.EntityFrameowrkCore.SqlServer，并未看到~.MySql的依赖（无法使用SqlDefaultDbContextMirgrationMoule基类），请问如何添加进去呢？
