### ISSUE TITLE
建议使用OData v4.0实现数据格式统一

### ISSUE THREAD

**Issue by Loongle** [dotnetcore/osharp#91]
现在各家的API数据返回格式都不一致
虽然大家都是基于RESTful 接口，但是数据格式大家都是千奇百怪的。
建议作者使用微软推出的工业级开放数据协议 ODdata v4.0 实现API返回格式。

https://www.odata.org/

实现该标准推行接口数据格式规范化

多谢！

**Comment by gmf520** [comment]
各人的需求不一样，框架上就没必要把技术方案定死了，需要OData的时候，自行实现难度也不大，API层的返回类型，基本属于UI层的事了，不属于框架核心功能
