### ISSUE TITLE
新加的Area不能生成中文权限列表，只是默认的Area名称

### ISSUE THREAD

**Issue by s641135196** [dotnetcore/osharp#92]
新加个area名称WorkOrder不能设置为中文
![image](https://user-images.githubusercontent.com/8079013/58541076-44262300-822d-11e9-9791-2f5a2ed84f4e.png)

再加了个控制器，生成的权限菜单，
![image](https://user-images.githubusercontent.com/8079013/58541152-6ddf4a00-822d-11e9-8394-9c1be1ab8f77.png)

如果要让WorkOrder变成中文“工单模块”， 得在源代码增加红色框代码。 
![image](https://user-images.githubusercontent.com/8079013/58541023-25279100-822d-11e9-87eb-d7cbbcf2e553.png)

**Comment by gmf520** [comment]
https://github.com/i66soft/osharp-docs-samples/blob/master/samples/Liuliu.Blogs/src/Liuliu.Blogs.Web/Areas/Admin/Controllers/Blogs/BlogController.cs#L26

**Comment by s641135196** [comment]
这样有试的， 不行的了， 在默认的Admin area下是没问题的。  因为我是新加的area.  这个area名称不能自定义为中文。

**Comment by gmf520** [comment]
添加一个 `AreaInfoAttribute` 特性类，用于代替 `AreaAttribute` 添加区域信息，支持区域的Display中文显示
```
    [AreaInfo("Admin", Display = "管理")]
    [RoleLimit]
    public abstract class AdminApiController : AreaApiController
    { }
```

**Comment by qinqoushui** [comment]
物理新增Area的话，会涉及到很多修改。
