### ISSUE TITLE
开源代码生成器插件

### ISSUE THREAD

**Issue by wangbs-dev** [dotnetcore/osharp#96]
您好，为了提高快速开发效率，能否开源咋们的代码生成器插件。因为每个项目的结构不一样，且需求不一样，能够自己定制代码生成器可以更好地快速开发，谢谢！望采纳。

**Comment by gmf520** [comment]
代码生成器涉及框架的商业模式，暂时不考虑开源，代码模板是支持自定义的，会出一些模板编写示例以供参考。

**Comment by wangbs-dev** [comment]
目前的代码模板可以自定义吗，我没有看到相关的文档说明。求指导

**Comment by wangbs-dev** [comment]
我看到咱们项目里面有CodeGenerator文件夹，里面好像是自定义的，但是这个里面的内容我修改了如何才能在插件里面使用呢，谢谢！

**Comment by gmf520** [comment]
有时间会搞个模板示例来演示如何自定义模板

**Comment by qinqoushui** [comment]
修改配置文件中相应的配置为你想用的模板文件
```
//"TemplateFile":"内置"
"TemplateFile": "D:/Code/....../Templates/ng_AlainComponentHtml.cshtml",
```
