### ISSUE TITLE
vs 代码生成插件 生成的代码报错

### ISSUE THREAD

**Issue by haiyoufan** [dotnetcore/osharp#99]
Hi 大大，我用代码生成插件碰到一个问题，请问是哪里错了吗？

System.InvalidOperationException:“指定的属性“string”在类型“My.Blogs.Blog.Entities.Article”中不存在。”

![image](https://user-images.githubusercontent.com/33166668/59149244-b83ea300-8a45-11e9-976e-eb0c9a1fa538.png)

**Comment by gmf520** [comment]
错误原因看不出来，不过你的配置完全是瞎搞啊，Title，Content怎么能是导航属性，不是导航属性就不该有关联实体

**Comment by haiyoufan** [comment]
谢谢！！我之前不知道导航属性是什么，所以乱写了。现在已经OK了。

**Comment by haiyoufan** [comment]
大大，代码生成器修改属性，不会自动变更代码的是吗，还是要怎么设置啊

**Comment by gmf520** [comment]
@haiyoufan 重新生成

**Comment by haiyoufan** [comment]
好的，谢谢啦

**Comment by haiyoufan** [comment]
大大好！我有一个问题想请教，我需要从另外一个数据库抓取数据，也想用Entity Framework，要怎么设置呢？？

**Comment by haiyoufan** [comment]
OSharp.Exceptions.OsharpException: '发现多个“Admin-BuildingX-Get”的功能信息，不允许重名'

這個怎麼處理啊，，，

**Comment by haiyoufan** [comment]
解決了，複製過來沒有改。。
[Area("Admin")]
[Area("Wenshidu")]

**Comment by gmf520** [comment]
有问题可以加群 85895249 交流，不要刷 issue

**Comment by haiyoufan** [comment]
好的
